[2025-01-24T08:16:16.019+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T08:16:16.625+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_first_dag.testing_first_task scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-24T08:16:17.062+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_first_dag.testing_first_task scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-24T08:16:17.085+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-24T08:16:17.579+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): testing_first_task> on 2025-01-21 00:00:00+00:00
[2025-01-24T08:16:17.987+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T08:16:18.102+0000] {standard_task_runner.py:72} INFO - Started process 94 to run task
[2025-01-24T08:16:18.095+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'testing_first_dag', 'testing_first_task', 'scheduled__2025-01-21T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/testing_dag.py', '--cfg-path', '/tmp/tmp2e81xqvu']
[2025-01-24T08:16:18.157+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask testing_first_task
[2025-01-24T08:16:19.460+0000] {task_command.py:467} INFO - Running <TaskInstance: testing_first_dag.testing_first_task scheduled__2025-01-21T00:00:00+00:00 [running]> on host 7400cb1053ee
[2025-01-24T08:16:22.323+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ikrar' AIRFLOW_CTX_DAG_ID='testing_first_dag' AIRFLOW_CTX_TASK_ID='testing_first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T00:00:00+00:00'
[2025-01-24T08:16:22.356+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T08:16:24.911+0000] {job.py:229} INFO - Heartbeat recovered after 11.21 seconds
[2025-01-24T08:16:25.600+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-24T08:16:25.681+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'Testing first task']
[2025-01-24T08:16:25.968+0000] {subprocess.py:99} INFO - Output:
[2025-01-24T08:16:26.105+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: Testing: command not found
[2025-01-24T08:16:26.116+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-01-24T08:16:26.491+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-24T08:16:27.074+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_first_dag, task_id=testing_first_task, run_id=scheduled__2025-01-21T00:00:00+00:00, execution_date=20250121T000000, start_date=20250124T081616, end_date=20250124T081627
[2025-01-24T08:16:27.451+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T08:16:27.467+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 68 for task testing_first_task (Bash command failed. The command returned a non-zero exit code 127.; 94)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-24T08:16:27.745+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-24T08:16:28.091+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T08:16:28.141+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-24T08:16:28.235+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
